import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'roles',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'value', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'residenciales',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'rfc', type: 'string', isOptional: true },
        { name: 'contact_name', type: 'string', isOptional: true },
        { name: 'contact_phone', type: 'string', isOptional: true },
        { name: 'active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'zones',
      columns: [
        { name: 'residencial_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'users',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'last_name', type: 'string', isOptional: true },
        { name: 'username', type: 'string', isIndexed: true },
        { name: 'active', type: 'boolean' },
        { name: 'shift_start', type: 'string', isOptional: true },
        { name: 'shift_end', type: 'string', isOptional: true },
        { name: 'is_logged_in', type: 'boolean' },
        { name: 'schedule_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'residencial_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'role_id', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'schedules',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'start_time', type: 'string' },
        { name: 'end_time', type: 'string' },
        { name: 'active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'locations',
      columns: [
        { name: 'residencial_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'zone_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'aisle', type: 'string', isOptional: true },
        { name: 'spot', type: 'string', isOptional: true },
        { name: 'number', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'is_occupied', type: 'boolean' },
        { name: 'active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'location_tasks',
      columns: [
        { name: 'location_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'req_photo', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'kardex',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'location_id', type: 'string', isIndexed: true },
        { name: 'timestamp', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'media', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'assignment_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'scan_type', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assignments',
      columns: [
        { name: 'guard_id', type: 'string', isIndexed: true },
        { name: 'location_id', type: 'string', isIndexed: true },
        { name: 'status', type: 'string' },
        { name: 'assigned_by', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assignment_tasks',
      columns: [
        { name: 'assignment_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'req_photo', type: 'boolean' },
        { name: 'completed', type: 'boolean' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'incident_categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'value', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'incident_types',
      columns: [
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'value', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'incidents',
      columns: [
        { name: 'guard_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'category_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'type_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'media', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'residencial_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'resolved_by_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds',
      columns: [
        { name: 'guard_id', type: 'string', isIndexed: true },
        { name: 'residencial_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'start_time', type: 'number' },
        { name: 'end_time', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'recurring_configuration_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'maintenances',
      columns: [
        { name: 'guard_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'category_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'type_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'media', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'resolved_by_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'recurring_configurations',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'residencial_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'recurring_locations',
      columns: [
        { name: 'recurring_configuration_id', type: 'string', isIndexed: true },
        { name: 'location_id', type: 'string', isIndexed: true },
        { name: 'order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'recurring_tasks',
      columns: [
        { name: 'recurring_location_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'req_photo', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
