# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
use_modular_headers!
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'checkapp' do
  # WatermelonDB depends on simdjson which is vendored via @nozbe/simdjson
  pod 'simdjson', :podspec => '../node_modules/@nozbe/simdjson/simdjson.podspec'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix fmt consteval errors in Xcode 16+
    fmt_header = 'Pods/fmt/include/fmt/base.h'
    if File.exist?(fmt_header)
      content = File.read(fmt_header)
      replacement = content.gsub('#  define FMT_CONSTEVAL consteval', '#  define FMT_CONSTEVAL constexpr')
      File.write(fmt_header, replacement) unless content == replacement
    end

    # Fix: simdjson podspec has a typo in the git URL
    simdjson_spec = '../node_modules/@nozbe/simdjson/simdjson.podspec'
    if File.exist?(simdjson_spec)
      content = File.read(simdjson_spec)
      fixed = content.gsub('simdmjson.git', 'simdjson.git')
      File.write(simdjson_spec, fixed) unless content == fixed
    end

    # Fix: Xcode 26+ User Script Sandboxing causes module resolution failures
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
